services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017

  backend:
    image: node:24-alpine
    restart: unless-stopped
    volumes:                   # 1. Create a virtual volume 
      - type: bind             # and bind it to the real folder
        source: .              # 2. Bind ./backend
        target: /app           # to /back (in the container)
    working_dir: /app          # 3. Set workdir to /app
    command: sh -c "node --run dev"       # 4. Run dev script in /app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    ports:
      - 3000:3000
